# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Bar Keep Server
version: "1.0.0"
slug: barKeepServer
description: A simple bar keepers recipie book app
url: "https://github.com/GovernmentHack/bar-keep-server/tree/main/barKeep"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  message: "configured hello world"
schema:
  message: "str?"
